kafka:
  cluster:
    bootstrapServer: 192.168.99.100:9092
  topic:
    name: abc
    numberOfPartitions: 1
    numberOfReplicas: 1


logging:
  level:
    root: INFO
    org.apache.kafka.clients: DEBUG